version: "3"
services:
  app:
    image: node:16.3.0-buster-slim
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/
    entrypoint: /bin/bash
    command: -c "su node && cd /home/node/ && yarn start"
